### ISSUE TITLE
Configurable products and MSI

### ISSUE THREAD

**Issue by simonjanguapa** [EmicoEcommerce/Magento2Tweakwise-archived#169] opened 2021-06-29 11:59 UTC
Issue Brief
--
After installing this extension for one of our customers we bumped in multiple store breaking issues.

Environment
--
* PHP Version: 7.3.27
* Magento Version: 2.4.1
* Tweakwise Version: 3.3.4
* Tweakwise Export Version: 3.3.0
* Magento Deploy Mode: production
* MSI (Multi Source Inventory) enabled and configured

Steps to reproduce
--
1. Install the Magento version stated above, add/import ~100K products (simple and configurable products).
2. Configure MSI (Multi Source Inventory) and add stock to configurable child products for different sources.
3. Let the Tweakwise Export cron run.

Actual result
--
1. Export won't run without cranking up the memory limit (so I have to run the export manually).
2. Configurable products are **not** exported after running the export manually while they have child products with actual stock.
3. All the (exported) products are visible in **all** the Magento 2 categories.
4. **All** the visible products have the core Magento 2 controller URL (like catalog/product/view/id).

Expected result
--
1. The export cron runs successfully, without any kind manual action.
2. The export contains all the configurable products that have child products with stock (based on MSI).
2. Products are only visible within their configured category/categories.
3. Products have the same URL-key as defined in the corresponding core attribute.

**Comment by Hnto** [comment] 2021-07-21 11:53
@simonjanguapa With regards to number 2 (Configurable products are not exported after running the export manually while they have child products with actual stock.): this has been fixed in version V3.2.0. **V3.3.0 was a wrong version and has been deleted** Please 'update' to v3.2.0.

**Comment by Hnto** [comment] 2022-01-05 09:36
@simonjanguapa Are you still experiencing these issues?

**Comment by Hnto** [comment] 2022-02-11 09:47
@simonjanguapa 

1. We are working on performance improvement
2. This is fixed in v3.2.0+
3. I'm not able to reproduce this
4. I'm not able to reproduce this

I will be closing this issue due to inactivity. Please create a new issue if you are still experiencing problems.

**Closed as completed by Hnto** 2022-02-11 09:47 UTC
