### ISSUE TITLE
Add robots meta tag to attribute landing pages

### ISSUE THREAD

**Issue by rlaven** [EmicoEcommerce/Magento2Tweakwise-archived#107] opened 2020-02-17 12:55 UTC
Issue Brief
--
It would be better for SEO purposes to set the robots meta tag on attribute landingpages to help the indexing of pages by spiders. 

Environment
--
* PHP Version: 7.2
* Magento Version: 2.3.2
* Tweakwise Version: 2.1.7
* Tweakwise Export Version: 1.5.0
* Magento Deploy Mode: Development
* Third party modules:
- emico/m2-attributelanding-tweakwise 1.0.2

Steps to reproduce
--
Install Magento 2.3.2
Install and configure Tweakwise
Install and configure attribute landing pages
Check the head of an attribute landing page via the browser inspector.

Actual result
--
The robots meta tag is not set on attribute landing pages

Expected result
--
The robots meta tag is set on attribute landing pages

**Comment by edwinljacobs** [comment] 2020-02-19 13:54
Hello,

I cannot reproduce your issue (on 2.3.1 and 2.3.4). Can you provide us with some extra debugging info?

The robots value should be resolved by Magento\Framework\View\Page\Config
```
/**
     * Retrieve URL to robots file
     *
     * @return string
     * @throws \Magento\Framework\Exception\LocalizedException
     */
    public function getRobots()
    {
        if ($this->getAreaResolver()->getAreaCode() !== Area::AREA_FRONTEND) {
            return 'NOINDEX,NOFOLLOW';
        }
        $this->build();
        if (empty($this->metadata[self::META_ROBOTS])) {
            $this->metadata[self::META_ROBOTS] = $this->scopeConfig->getValue(
                'design/search_engine_robots/default_robots',
                \Magento\Store\Model\ScopeInterface::SCOPE_STORE
            );
        }
        return $this->metadata[self::META_ROBOTS];
    }
```

And after that it will be processed by \Emico\Tweakwise\Model\Seo\Robots\Plugin
```
/**
     * @param PageConfig $config
     * @param $result
     * @return string
     */
    public function afterGetRobots(PageConfig $config, $result)
    {
        if (!$this->tweakwiseConfig->isSeoEnabled()) {
            return $result;
        }

        if ($this->isAlreadyNoIndex($result)) {
            return $result;
        }

        if (!$this->shouldApplyNoindex()) {
            return $result;
        }

        return $this->getNewRobots($result);
    }
```
Can you tell me what the initial outcome of getRobots is?

**Closed as completed** 2020-03-18 12:21 UTC
